#!/usr/bin/env ruby

require 'rubygems'
require 'highline/import'
require 'pathname'

require File.join(File.dirname(Pathname.new($0).realpath), 'pwdhash')

VERSION_FILE = File.join(File.dirname(Pathname.new($0).realpath), "VERSION")

def usage
    puts "pwdhash.rb #{version} - Chris Yuen, Chris Roos (2010)"
    puts "Usage: pwdhash REALM"
    exit
end

def version
    open(VERSION_FILE).read.chomp
end

usage if ARGV.length != 1

realm = ARGV[0].chomp

hl = HighLine.new($stdin, $stderr)
password = hl.ask("Password for #{realm}: "){ |q| q.echo = false }

puts get_hashed_password(password, realm)
