#!/usr/bin/env ruby

require 'rubygems'
require 'highline/import'
require 'pathname'

require File.join(File.dirname(Pathname.new($0).realpath), 'pwdhash')
require File.join(File.dirname(Pathname.new($0).realpath), 'extract_domain')

VERSION_FILE = File.join(File.dirname(Pathname.new($0).realpath), "VERSION")

def usage
    puts "pwdhash.rb #{version} - Chris Yuen, Chris Roos (2010)"
    puts "Usage: pwdhash URI"
    puts "Example: pwdhash https://mail.google.com"
    exit
end

def version
    open(VERSION_FILE).read.chomp
end

usage if ARGV.length != 1

realm = extract_domain(ARGV[0].chomp)

hl = HighLine.new($stdin, $stderr)
password = hl.ask("Password for #{realm}: "){ |q| q.echo = false }

print get_hashed_password(password, realm)
