#!/usr/bin/env ruby

require 'rubygems'
require 'highline/import'
require 'pathname'

require File.join(Pathname.new($0).realpath, 'pwdhash')

def usage
    puts "Usage: pwdhash REALM"
    exit
end

usage if ARGV.length != 1

realm = ARGV[0].chomp

hl = HighLine.new($stdin, $stderr)
password = hl.ask("Password for #{realm}: "){ |q| q.echo = false }

puts get_hashed_password(password, realm)
